projects:
  callstatus:
    schemaPath: app/src/main/graphql/schema.json
    includes:
      - app/src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app/src/main/graphql/com/amazonaws/amplify/generated/graphql
        graphQLApiId: gf3tqmsr4jcchlnqsqhljj4wru
      endpoints:
        prod: >-
          https://5aopt4ipdzgrbjqi54o7bmlt3u.appsync-api.us-east-1.amazonaws.com/graphql
